<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>1.0.0</Version>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    </PropertyGroup>

    <PropertyGroup>
        <Author>YF</Author>
        <Name>RealTorch</Name>
        <Description>Makes the torch accessory put out light.</Description>
        <Punchline>Set the world alight!</Punchline>
        <InternalName>RealTorch</InternalName>
        <Tags>torch;light;accessory;roleplay</Tags>
    </PropertyGroup>
</Project>
